---
- hosts: myctlxc
  tags: deployment
  gather_facts: no
  vars_files:
    - vars/vault.yml
  roles:
    - role: proxmox-lxc-deploy-init/deployment

- hosts: myctlxc
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
  - name: MISE À JOUR SYSTÈME
    become: true
    apt:
      update_cache: true
      upgrade: true
      cache_valid_time: 14400
  roles:
    - role: proxmox-lxc-deploy-init/setup