---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: CONFIGURATION DES PARAMÈTRES RÉGIONAUX
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales }}"
  register: locale_gen_result
  become: true

- name: INSTALLATION/CONFIGURATION DU MESSAGE OF THE DAY (MOTD)
  include_tasks: includes/motd.yml

- name: INSTALLATION/CONFIGURATION DE zellij
  include_tasks: includes/zellij.yml